# JIRA Configuration
jira.base-url=https://issues.apache.org/jira


# Server Configuration
server.port=9090
spring.application.name=Atlassian Analyzer

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

logging.level.ru.spbstu.atlassiananalyzer=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG